# Generated by Django 6.0.6 on 2026-06-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('tecnologia', models.CharField(choices=[('FO', 'Fibra Óptica'), ('RE', 'Radioenlace'), ('ETH', 'Ethernet / Cobre')], default='FO', max_length=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMetricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ONLINE', 'Online'), ('DEGRADADO', 'Degradado'), ('OFFLINE', 'Offline')], max_length=10)),
                ('latencia', models.FloatField()),
                ('perdida', models.IntegerField()),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='monitor_app.nodo')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
