# Generated by Django 6.0.6 on 2026-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmetricas',
            name='snmp_cpu',
            field=models.IntegerField(blank=True, help_text='Uso de CPU %', null=True),
        ),
        migrations.AddField(
            model_name='historialmetricas',
            name='snmp_ram',
            field=models.IntegerField(blank=True, help_text='Uso de RAM %', null=True),
        ),
        migrations.AddField(
            model_name='historialmetricas',
            name='velocidad_max_download',
            field=models.FloatField(blank=True, help_text='Mbps de Bajada (Speedtest)', null=True),
        ),
        migrations.AddField(
            model_name='nodo',
            name='comunidad_snmp',
            field=models.CharField(blank=True, default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='nodo',
            name='monitoreo_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nodo',
            name='snmp_activo',
            field=models.BooleanField(default=False),
        ),
    ]
