# Generated by Django 6.0.6 on 2026-06-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_configuracionglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmetricas',
            name='velocidad_max_subida',
            field=models.FloatField(blank=True, help_text='Mbps de Subida', null=True),
        ),
    ]
